# Generated by Django 4.1.3 on 2022-11-25 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=225, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('message', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, default=None, null=True)),
                ('user_name', models.CharField(blank=True, default=None, max_length=225, null=True)),
                ('parent_name', models.CharField(blank=True, default=None, max_length=225, null=True)),
                ('parent_comment', models.TextField(blank=True, default=None, null=True)),
                ('datestamp', models.CharField(blank=True, default=None, max_length=225, null=True)),
                ('timestamp', models.CharField(blank=True, default=None, max_length=225, null=True)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.videocomment')),
            ],
        ),
    ]
